# Generated by Django 2.0.5 on 2018-05-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Foster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=70)),
                ('PHONE', models.CharField(max_length=12)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('BIRTH_DATE', models.DateField()),
                ('ENTRY_DATE', models.DateField()),
                ('DAPARTURE_DATE', models.DateField(blank=True, null=True)),
                ('TYPE', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], default='DOG', max_length=10)),
                ('SEX', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('STATUS', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('URGENCY', 'Urgency')], default='Unavailable', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='foster',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='foster',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pet'),
        ),
        migrations.AddField(
            model_name='adopterfamily',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='adopterfamily',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pet'),
        ),
    ]
