# Generated by Django 2.0.5 on 2018-05-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('entry_date', models.DateField(verbose_name='Fecha de entrada')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('animal_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], default='DOG', max_length=10, verbose_name='Tipo')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10, verbose_name='Sexo')),
                ('state', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('URGENCY', 'Urgency')], default='Unavailable', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Foster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=70, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=12, verbose_name='Telefono')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='foster',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='adopterfamily',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Animal'),
        ),
        migrations.AddField(
            model_name='adopterfamily',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
    ]
