# Generated by Django 2.0.5 on 2018-05-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopterfamily',
            old_name='person',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='adopterfamily',
            old_name='pet',
            new_name='Pet',
        ),
        migrations.RenameField(
            model_name='foster',
            old_name='person',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='foster',
            old_name='pet',
            new_name='Pet',
        ),
    ]
