# Generated by Django 2.0.5 on 2018-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='state',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('URGENCY', 'Urgency')], default='UNAVAILABLE', max_length=10, verbose_name='Estado'),
        ),
    ]
