# Generated by Django 2.0.5 on 2018-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180514_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ADDRESS',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='LAST_NAME',
            field=models.CharField(max_length=70, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='NAME',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PHONE',
            field=models.CharField(max_length=12, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='BIRTH_DATE',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='DAPARTURE_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='ENTRY_DATE',
            field=models.DateField(verbose_name='Fecha de entrada'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='SEX',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='STATUS',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('URGENCY', 'Urgency')], default='Unavailable', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='TYPE',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], default='DOG', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
