# Generated by Django 2.0.5 on 2018-05-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180515_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopterfamily',
            old_name='Person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='adopterfamily',
            old_name='Pet',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='foster',
            old_name='Person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='foster',
            old_name='Pet',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='ADDRESS',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='EMAIL',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='LAST_NAME',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='PHONE',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='BIRTH_DATE',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='DAPARTURE_DATE',
            new_name='departure_date',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='ENTRY_DATE',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='TYPE',
            new_name='pet_type',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='SEX',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='STATUS',
            new_name='state',
        ),
    ]
