# Generated by Django 2.0.5 on 2018-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180516_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='state',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No Disponible'), ('URGENCY', 'Urgente')], default='UNAVAILABLE', max_length=50, verbose_name='Estado'),
        ),
    ]
