# Generated by Django 2.0.5 on 2018-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180518_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('BIG', 'Grande'), ('MEDIUM', 'Mediano'), ('LITTLE', 'Pequeño')], default='MEDIUM', max_length=50, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato')], default='DOG', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Macho'), ('FEMALE', 'Hembra')], default='MALE', max_length=50, verbose_name='Sexo'),
        ),
    ]
