# Generated by Django 2.0.5 on 2018-05-24 13:27

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180523_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='', verbose_name='Imaxe'),
        ),
    ]
