# Generated by Django 2.0.5 on 2018-05-24 13:35

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/', verbose_name='Imaxe'),
        ),
    ]
