# Generated by Django 2.0.5 on 2018-05-24 13:39

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180524_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen'),
        ),
    ]
