# Generated by Django 2.0.5 on 2018-05-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180524_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='picture',
            new_name='image',
        ),
    ]
