# Generated by Django 2.0.5 on 2018-05-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180524_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
    ]
