# Generated by Django 2.0.5 on 2018-05-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_animal_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='person',
        ),
        migrations.AlterField(
            model_name='adopterfamily',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='core.Person'),
        ),
    ]
