# Generated by Django 2.0.5 on 2018-05-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180528_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
