# Generated by Django 2.0.5 on 2018-05-28 12:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180528_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
