quotes = {
    '“Todo el conocimiento, la totalidad de preguntas y respuestas se encuentran en el perro”.': 'Franz Kafka.',
    '“Amo a los perros porque nunca le hacen sentir a uno que los haya tratado mal”.': 'Otto von Bismark.',
    '“El amor por los animales eleva el nivel cultural del pueblo”.': 'Fermín Salvochea.',
    '“El perro es parte del hombre”.': 'Albert Brahm.',
    '“Una vida sin perro es un error”.': 'Carl Zuckmayer.',
    '“Tener compasión de todos los seres vivos es lo que hace al hombre realmente humano”.': 'Albert Schweitzer.',
    '“El amor por todas las criaturas vivientes es el más noble atributo del hombre”.': 'Charles Darwin.',
    '“Hasta que no hayas amado a un animal, parte de tu alma estará dormida”.': 'Anatole France.',
    '“No hay psiquiatra en el mundo como un cachorro lamiéndote la cara”.': 'Ben Williams.',
    '“El perro es un caballero. Espero llegar a su paraíso, y no al del hombre”.': 'Mark Twain.',
    '“El dinero puede comprarte un lindo perrito, pero no puede comprar que sacuda su cola”.': 'Henry Wheeler Shaw.',
    '“Nadie aprecia el genio innato de tu conversación como lo hace tu perro”.': 'Christopher Morley.',
    '“El más pequeño felino es una obra maestra”': 'Leonardo da Vinci.',
    "“'Miau' significa 'guau' en el lenguaje gatuno.”": 'George Carlin.',
    '“El tiempo pasado con un gato nunca se pierde.”': 'Colette.',
    '“He vivido con varios maestros Zen, todos ellos gatos.”': 'Eckhart Tolle.',
    '“Errar es humano, ronronear es felino.”': 'Robert Byrne.',
    '“Si pretendes escribir, ten gatos.”': 'Aldous Huxley.',
    }